### ISSUE TITLE
FD stops playback when one of the connected speakers get switched of

### ISSUE THREAD

**Issue by LordMyschkin** [owntone/forked-daapd#1196] opened 2021-02-24 11:47 UTC
I am using latest master branch build on Raspberry pi4 - although the behavior (not even sure it is a bug or by design) bothers me a about a year:

I use forked-daapd to spread music above my flat, using 2 GGMMs-e5 (cheap mobile WLAN SPeakers), 2 Sonos and one other.

When one of the GGMM-Speakers gets disconnected, Forked-daapd changes state to paused
log shows
[2021-02-24 10:02:37] [  LOG]     dacp: Request for artwork without mw parameter
[2021-02-24 10:02:48] [  LOG]     dacp: (LOGGING SKIPPED - above log message is repeating)
[2021-02-24 12:14:56] [  LOG]     dacp: 'device-prevent-playback' request from '192.168.2.23' has unknown Active-Remote: '1818116480'
[2021-02-24 12:14:56] [  LOG]     dacp: 'device-busy' request from '192.168.2.23' has unknown Active-Remote: '1818116480'
[2021-02-24 12:14:56] [  LOG]     dacp: 'device-prevent-playback' request from '192.168.2.23' has unknown Active-Remote: '1818116480'
[2021-02-24 12:15:25] [  LOG]     dacp: Request for artwork without mw parameter

I just have to restart playback to resume, so no crash.

**Comment by ejurgensen** [comment] 2021-02-24 11:52
Playback should only be paused when the last active speaker is disconnected. I understand that is not the case here, so it sounds like a bug. I will investigate what might be happening and get back to you.

**Comment by ejurgensen** [comment] 2021-02-25 14:55
I checked this, and I can't see what is causing this. I also tested, and couldn't reproduce. Can you share debug level logs? - maybe they can clue me in on what is happening.

**Comment by ejurgensen** [comment] 2021-03-07 00:02
Closing, no feedback

**Comment by LordMyschkin** [comment] 2021-03-11 22:05
Sorry, I was not at home for a while: here is the log of this event - could you please reopen?
[forked-daapd-error.log](https://github.com/ejurgensen/forked-daapd/files/6126227/forked-daapd-error.log)

**Comment by ejurgensen** [comment] 2021-03-11 22:41
Checked the log, the reason playback stops is simple enough - someone is asking forked-daapd to pause:

`[2021-03-11 22:52:53] [DEBUG]     dacp: DACP request: '/ctrl-int/1/pause'`

I assume the device making this request is the one being switched off, but I can't see that from the log.

In addition to this, I notice that within the same second the GGMM_R is spewing quite a number of requests:

```
[2021-03-11 22:52:53] [DEBUG]     dacp: DACP request: '/ctrl-int/1/setproperty?dmcp.device-prevent-playback=1'
[2021-03-11 22:52:53] [DEBUG]   player: Speaker prevent playback: 'GGMM_R' (id=147847004544)
...
[2021-03-11 22:52:53] [DEBUG]     dacp: DACP request: '/ctrl-int/1/setproperty?dmcp.device-busy=1'
[2021-03-11 22:52:53] [DEBUG]   player: Speaker busy: 'GGMM_R' (id=147847004544)
...
[2021-03-11 22:52:53] [DEBUG]     dacp: DACP request: '/ctrl-int/1/setproperty?dmcp.device-prevent-playback=0'
[2021-03-11 22:52:53] [DEBUG]   player: Speaker prevent playback: 'GGMM_R' (id=147847004544)
...
[2021-03-11 22:52:53] [DEBUG]     dacp: DACP request: '/ctrl-int/1/setproperty?dmcp.device-prevent-playback=1'
[2021-03-11 22:52:53] [DEBUG]   player: Speaker prevent playback: 'GGMM_R' (id=147847004544)
...
[2021-03-11 22:52:53] [DEBUG]     dacp: DACP request: '/ctrl-int/1/setproperty?dmcp.device-busy=1'
[2021-03-11 22:52:53] [DEBUG]   player: Speaker busy: 'GGMM_R' (id=147847004544)
...
[2021-03-11 22:52:53] [DEBUG]     dacp: DACP request: '/ctrl-int/1/setproperty?dmcp.device-prevent-playback=0'
[2021-03-11 22:52:53] [DEBUG]   player: Speaker prevent playback: 'GGMM_R' (id=147847004544)
...
[2021-03-11 22:52:53] [DEBUG]     dacp: DACP request: '/ctrl-int/1/pause'
...
[2021-03-11 22:52:53] [DEBUG]     dacp: DACP request: '/ctrl-int/1/setproperty?dmcp.device-prevent-playback=1'
[2021-03-11 22:52:53] [DEBUG]   player: Speaker prevent playback: 'GGMM_R' (id=147847004544)
...
[2021-03-11 22:52:53] [DEBUG]     dacp: DACP request: '/ctrl-int/1/setproperty?dmcp.device-busy=1'
[2021-03-11 22:52:53] [DEBUG]   player: Speaker busy: 'GGMM_R' (id=147847004544)

```

Seems a bit weird?

**Comment by LordMyschkin** [comment] 2021-03-12 15:51
So a problem of GGMM and not of forked-daapd; seems like GGMM did not expect someone could buy more than one of their speakers ;-)
thank you for inspecting the issue though

**Closed** 2021-03-31 19:33 UTC
